name: CI Workflow

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint PHP Files
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file";
          done

  build:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t khalilz00/mon-nginx-image:latest .

  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push khalilz00/mon-nginx-image:latest

  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - name: Login to SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Pull image from Docker Hub
        run: |
          docker pull khalilz00/mon-nginx-image:latest
          
          
          
          # script: |
          #   docker pull khalilz00/mon-nginx-image:latest
          #   docker-compose -f your-docker-compose-file.yml up -d

